api = "0.7"

[buildpack]
  description = "A buildpack designed to resolve permission issues for the Ruby on Rails './tmp' directory"
  homepage = "https://github.com/migetapp/rails-chmod-buildpack"
  id = "miget/rails-chmod-buildpack"
  keywords = ["ruby", "mri", "chmod"]
  name = "Miget Buildpack for Paketo MRI"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/migetapp/rails-chmod-buildpack/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
